spring:
  application:
    name: fast
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring6
    username: root
    password: root
    hikari:
      auto-commit: true
      maximum-pool-size: 10
      minimum-idle: 10
      connection-test-query: select 1
      connection-timeout: 20000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.mybatisplus.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080
